import { initializeApp } from 'firebase/app';
import { getFirestore, collection, addDoc, serverTimestamp } from 'firebase/firestore';

const firebaseConfig = {
    apiKey: "AIzaSyC4jFJ3jCXd7Q5nydQaBSQWaVKvFhTkmJs",
    authDomain: "expertene-59771.firebaseapp.com",
    projectId: "expertene-59771",
    storageBucket: "expertene-59771.firebasestorage.app",
    messagingSenderId: "284086686035",
    appId: "1:284086686035:web:f7f79f6730d430db7091a6",
    measurementId: "G-0GQ6P1ML29",
};

const app = initializeApp(firebaseConfig, 'seed-report-app');
const db = getFirestore(app);

async function seedReport() {
    try {
        console.log("Seeding a test report...");
        await addDoc(collection(db, 'reports'), {
            articleId: "test-article-id",
            reporterId: "test-reporter-id",
            reason: "This is a test report generated by the system.",
            status: "pending",
            createdAt: serverTimestamp()
        });
        console.log("Test report created successfully.");
        process.exit(0);
    } catch (error) {
        console.error("Error creating test report:", error);
        process.exit(1);
    }
}

seedReport();
